#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKFLOW="$ROOT_DIR/.github/workflows/deploy.yml"
GITIGNORE="$ROOT_DIR/.gitignore"
DOCKERIGNORE="$ROOT_DIR/.dockerignore"
DOCKERFILE="$ROOT_DIR/Dockerfile"
CADDYFILE="$ROOT_DIR/Caddyfile"
COMPOSE_FILE="$ROOT_DIR/docker-compose.yml"
SETUP_SCRIPT="$ROOT_DIR/scripts/setup-server-env.sh"
VERIFY_SCRIPT="$ROOT_DIR/scripts/verify-public-site.sh"
DEPLOY_SCRIPT="$ROOT_DIR/scripts/deploy.sh"
ROLLBACK_SCRIPT="$ROOT_DIR/scripts/rollback-env.sh"
PREFLIGHT_SCRIPT="$ROOT_DIR/scripts/deploy-preflight.sh"
ENV_CHECK_SCRIPT="$ROOT_DIR/scripts/check-env-file.sh"
ENV_TEST_SCRIPT="$ROOT_DIR/scripts/test-env-file.sh"
DEPLOY_SECRETS_SCRIPT="$ROOT_DIR/scripts/check-deploy-secrets.sh"
DEPLOY_SECRETS_TEST_SCRIPT="$ROOT_DIR/scripts/test-deploy-secrets.sh"
GITHUB_SECRETS_SCRIPT="$ROOT_DIR/scripts/check-github-secrets.sh"
GITHUB_SECRETS_TEST_SCRIPT="$ROOT_DIR/scripts/test-github-secrets.sh"
GITHUB_SECRETS_COMMAND_SCRIPT="$ROOT_DIR/scripts/print-github-secrets-commands.sh"
GITHUB_SECRETS_COMMAND_TEST_SCRIPT="$ROOT_DIR/scripts/test-print-github-secrets-commands.sh"
REMOTE_SERVER_SCRIPT="$ROOT_DIR/scripts/check-remote-server.sh"
REMOTE_SERVER_TEST_SCRIPT="$ROOT_DIR/scripts/test-remote-server-check.sh"
DOMAIN_ROUTING_SCRIPT="$ROOT_DIR/scripts/check-domain-routing.sh"
DOMAIN_ROUTING_TEST_SCRIPT="$ROOT_DIR/scripts/test-domain-routing.sh"
DEPLOY_DRY_RUN_TEST_SCRIPT="$ROOT_DIR/scripts/test-deploy-dry-run.sh"
DEPLOY_PREFLIGHT_TEST_SCRIPT="$ROOT_DIR/scripts/test-deploy-preflight.sh"
DEPLOY_RETRY_TEST_SCRIPT="$ROOT_DIR/scripts/test-deploy-retry.sh"
ROLLBACK_TEST_SCRIPT="$ROOT_DIR/scripts/test-rollback-env.sh"
LAUNCH_TEST_SCRIPT="$ROOT_DIR/scripts/test-launch-readiness.sh"
LAUNCH_SCRIPT="$ROOT_DIR/scripts/check-launch-readiness.sh"
SEO_SCRIPT="$ROOT_DIR/scripts/check-frontend-seo.sh"
BUNDLE_SCRIPT="$ROOT_DIR/scripts/check-frontend-bundles.sh"
RENDER_SCRIPT="$ROOT_DIR/scripts/check-frontend-render.sh"
AVATAR_IMAGE="$ROOT_DIR/frontend/public/avatar/shouka-avatar.png"
RELEASE_SCRIPT="$ROOT_DIR/scripts/verify-release.sh"
LOCKFILE_SCRIPT="$ROOT_DIR/scripts/check-frontend-lockfile.mjs"
CADDY_SMOKE_SCRIPT="$ROOT_DIR/scripts/smoke-caddy-proxy.sh"
README="$ROOT_DIR/README.md"
LAUNCH_CHECKLIST="$ROOT_DIR/docs/launch-checklist.md"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

pass() {
  echo "OK: $*"
}

[[ -f "$WORKFLOW" ]] || fail "missing .github/workflows/deploy.yml"
[[ -f "$GITIGNORE" ]] || fail "missing .gitignore"
[[ -f "$DOCKERIGNORE" ]] || fail "missing .dockerignore"
[[ -f "$DOCKERFILE" ]] || fail "missing Dockerfile"
[[ -f "$COMPOSE_FILE" ]] || fail "missing docker-compose.yml"
[[ -f "$CADDYFILE" ]] || fail "missing Caddyfile"
[[ -x "$SETUP_SCRIPT" ]] || fail "missing executable scripts/setup-server-env.sh"
[[ -x "$VERIFY_SCRIPT" ]] || fail "missing executable scripts/verify-public-site.sh"
[[ -x "$DEPLOY_SCRIPT" ]] || fail "missing executable scripts/deploy.sh"
[[ -x "$ROLLBACK_SCRIPT" ]] || fail "missing executable scripts/rollback-env.sh"
[[ -x "$PREFLIGHT_SCRIPT" ]] || fail "missing executable scripts/deploy-preflight.sh"
[[ -x "$ENV_CHECK_SCRIPT" ]] || fail "missing executable scripts/check-env-file.sh"
[[ -x "$ENV_TEST_SCRIPT" ]] || fail "missing executable scripts/test-env-file.sh"
[[ -x "$DEPLOY_SECRETS_SCRIPT" ]] || fail "missing executable scripts/check-deploy-secrets.sh"
[[ -x "$DEPLOY_SECRETS_TEST_SCRIPT" ]] || fail "missing executable scripts/test-deploy-secrets.sh"
[[ -x "$GITHUB_SECRETS_SCRIPT" ]] || fail "missing executable scripts/check-github-secrets.sh"
[[ -x "$GITHUB_SECRETS_TEST_SCRIPT" ]] || fail "missing executable scripts/test-github-secrets.sh"
[[ -x "$GITHUB_SECRETS_COMMAND_SCRIPT" ]] || fail "missing executable scripts/print-github-secrets-commands.sh"
[[ -x "$GITHUB_SECRETS_COMMAND_TEST_SCRIPT" ]] || fail "missing executable scripts/test-print-github-secrets-commands.sh"
[[ -x "$REMOTE_SERVER_SCRIPT" ]] || fail "missing executable scripts/check-remote-server.sh"
[[ -x "$REMOTE_SERVER_TEST_SCRIPT" ]] || fail "missing executable scripts/test-remote-server-check.sh"
[[ -x "$DOMAIN_ROUTING_SCRIPT" ]] || fail "missing executable scripts/check-domain-routing.sh"
[[ -x "$DOMAIN_ROUTING_TEST_SCRIPT" ]] || fail "missing executable scripts/test-domain-routing.sh"
[[ -x "$DEPLOY_DRY_RUN_TEST_SCRIPT" ]] || fail "missing executable scripts/test-deploy-dry-run.sh"
[[ -x "$DEPLOY_PREFLIGHT_TEST_SCRIPT" ]] || fail "missing executable scripts/test-deploy-preflight.sh"
[[ -x "$DEPLOY_RETRY_TEST_SCRIPT" ]] || fail "missing executable scripts/test-deploy-retry.sh"
[[ -x "$ROLLBACK_TEST_SCRIPT" ]] || fail "missing executable scripts/test-rollback-env.sh"
[[ -x "$LAUNCH_TEST_SCRIPT" ]] || fail "missing executable scripts/test-launch-readiness.sh"
[[ -x "$LAUNCH_SCRIPT" ]] || fail "missing executable scripts/check-launch-readiness.sh"
[[ -x "$SEO_SCRIPT" ]] || fail "missing executable scripts/check-frontend-seo.sh"
[[ -x "$BUNDLE_SCRIPT" ]] || fail "missing executable scripts/check-frontend-bundles.sh"
[[ -x "$RENDER_SCRIPT" ]] || fail "missing executable scripts/check-frontend-render.sh"
[[ -f "$AVATAR_IMAGE" ]] || fail "missing frontend/public/avatar/shouka-avatar.png"
[[ -x "$RELEASE_SCRIPT" ]] || fail "missing executable scripts/verify-release.sh"
[[ -f "$LOCKFILE_SCRIPT" ]] || fail "missing scripts/check-frontend-lockfile.mjs"
[[ -x "$CADDY_SMOKE_SCRIPT" ]] || fail "missing executable scripts/smoke-caddy-proxy.sh"
[[ -f "$LAUNCH_CHECKLIST" ]] || fail "missing docs/launch-checklist.md"

grep -q "workflow_dispatch:" "$WORKFLOW" || fail "deploy workflow must support manual runs"
grep -q "pull_request:" "$WORKFLOW" || fail "deploy workflow must run verification for pull requests"
awk '
  /^  pull_request:/ { in_trigger=1; next }
  /^  [a-z_]+:/ { if (in_trigger) in_trigger=0 }
  in_trigger && /- main/ { found=1 }
  END { exit found ? 0 : 1 }
' "$WORKFLOW" || fail "deploy workflow pull request trigger must target main"
awk '
  /^  verify:/ { in_job=1 }
  /^  deploy:/ { in_job=0 }
  in_job && /timeout-minutes: 45/ { found=1 }
  END { exit found ? 0 : 1 }
' "$WORKFLOW" || fail "verify job must have a 45 minute timeout"
awk '
  /^  deploy:/ { in_job=1 }
  in_job && /timeout-minutes: 60/ { found=1 }
  END { exit found ? 0 : 1 }
' "$WORKFLOW" || fail "deploy job must have a 60 minute timeout"
grep -q "scripts/verify-release.sh" "$WORKFLOW" || fail "deploy workflow must run release verification"
grep -q "scripts/deploy.sh" "$WORKFLOW" || fail "deploy workflow must call scripts/deploy.sh"
grep -q "npm --prefix frontend audit --audit-level=high" "$WORKFLOW" || fail "deploy workflow must block high-severity frontend dependency advisories"
grep -q "playwright install --with-deps chromium" "$WORKFLOW" || fail "deploy workflow must install Chromium for browser render checks"
grep -q "scripts/smoke-production.sh" "$RELEASE_SCRIPT" || fail "release verification must run production smoke test"
grep -q "scripts/check-frontend-lockfile.mjs" "$RELEASE_SCRIPT" || fail "release verification must check frontend lockfile consistency"
grep -q "npm --prefix frontend test" "$RELEASE_SCRIPT" || fail "release verification must run frontend tests"
grep -q "scripts/check-frontend-bundles.sh" "$RELEASE_SCRIPT" || fail "release verification must enforce frontend bundle size"
grep -q "scripts/check-frontend-render.sh" "$RELEASE_SCRIPT" || fail "release verification must syntax-check browser render checks"
grep -q "scripts/test-env-file.sh" "$RELEASE_SCRIPT" || fail "release verification must run env validation tests"
grep -q "scripts/test-deploy-secrets.sh" "$RELEASE_SCRIPT" || fail "release verification must run deploy secret validation tests"
grep -q "scripts/test-github-secrets.sh" "$RELEASE_SCRIPT" || fail "release verification must run GitHub secret name tests"
grep -q "scripts/print-github-secrets-commands.sh" "$RELEASE_SCRIPT" || fail "release verification must syntax-check GitHub secret command printer"
grep -q "scripts/test-print-github-secrets-commands.sh" "$RELEASE_SCRIPT" || fail "release verification must run GitHub secret command printer tests"
grep -q "scripts/test-remote-server-check.sh" "$RELEASE_SCRIPT" || fail "release verification must run remote server check tests"
grep -q "scripts/test-domain-routing.sh" "$RELEASE_SCRIPT" || fail "release verification must run domain routing tests"
grep -q "scripts/test-deploy-dry-run.sh" "$RELEASE_SCRIPT" || fail "release verification must run deploy dry-run tests"
grep -q "scripts/test-deploy-preflight.sh" "$RELEASE_SCRIPT" || fail "release verification must run deploy preflight tests"
grep -q "scripts/test-deploy-retry.sh" "$RELEASE_SCRIPT" || fail "release verification must run deploy retry tests"
grep -q "scripts/test-rollback-env.sh" "$RELEASE_SCRIPT" || fail "release verification must run rollback env tests"
grep -q "scripts/test-launch-readiness.sh" "$RELEASE_SCRIPT" || fail "release verification must run launch readiness tests"
grep -q "scripts/check-frontend-render.sh" "$ROOT_DIR/scripts/smoke-production.sh" || fail "production smoke test must run browser render checks"
grep -q "canonical URL" "$ROOT_DIR/scripts/smoke-production.sh" || fail "production smoke test must verify canonical URL metadata"
grep -q "og:url" "$ROOT_DIR/scripts/smoke-production.sh" || fail "production smoke test must verify Open Graph URL metadata"
grep -q "twitter:image" "$ROOT_DIR/scripts/smoke-production.sh" || fail "production smoke test must verify Twitter image metadata"
grep -q "share image asset" "$ROOT_DIR/scripts/smoke-production.sh" || fail "production smoke test must verify the share image asset is reachable"
grep -q "creator avatar asset" "$ROOT_DIR/scripts/smoke-production.sh" || fail "production smoke test must verify the creator avatar asset is reachable"
grep -q "Shouka creator avatar" "$ROOT_DIR/frontend/src/pages/Home.tsx" || fail "homepage must render the creator avatar"
grep -q "Shouka creator avatar" "$ROOT_DIR/frontend/scripts/check-render.mjs" || fail "browser render check must verify the creator avatar"
grep -q "scripts/check-remote-server.sh" "$LAUNCH_SCRIPT" || fail "launch readiness must support remote server checks"
grep -q "scripts/check-github-secrets.sh" "$LAUNCH_SCRIPT" || fail "launch readiness must support GitHub secret checks"
grep -q -- "--github-secrets" "$LAUNCH_SCRIPT" || fail "launch readiness must expose --github-secrets"
grep -q -- "--require-deploy-env" "$LAUNCH_SCRIPT" || fail "launch readiness must expose --require-deploy-env"
grep -q -- "--remote-server" "$LAUNCH_SCRIPT" || fail "launch readiness must expose --remote-server"
grep -q "scripts/check-domain-routing.sh" "$LAUNCH_SCRIPT" || fail "launch readiness must support domain routing checks"
grep -q -- "--domain-routing" "$LAUNCH_SCRIPT" || fail "launch readiness must expose --domain-routing"
grep -q -- "--expected-version" "$LAUNCH_SCRIPT" || fail "launch readiness must expose --expected-version"
grep -q -- "--expect-caddy-headers" "$LAUNCH_SCRIPT" || fail "launch readiness must expose --expect-caddy-headers"
grep -q "docker build" "$WORKFLOW" || fail "deploy workflow must verify the Docker image builds"
grep -q "caddy validate" "$WORKFLOW" || fail "deploy workflow must validate Caddyfile syntax"
grep -q "caddy:2" "$WORKFLOW" || fail "deploy workflow must use the official Caddy image for validation"
grep -q "scripts/smoke-caddy-proxy.sh" "$WORKFLOW" || fail "deploy workflow must smoke-test the Caddy reverse proxy path"
awk '
  /name: Smoke test Caddy reverse proxy/ { in_step=1 }
  in_step && /timeout-minutes: 15/ { found=1 }
  in_step && /name: Build deployment Docker image/ { in_step=0 }
  END { exit found ? 0 : 1 }
' "$WORKFLOW" || fail "Caddy reverse proxy smoke test must have a 15 minute CI timeout"
grep -q -- "--build-arg APP_VERSION" "$WORKFLOW" || fail "deploy workflow must pass APP_VERSION to Docker builds"
grep -q "shouka-blog:ci" "$WORKFLOW" || fail "deploy workflow must tag the CI Docker build"
grep -q "docker run" "$WORKFLOW" || fail "deploy workflow must run the CI Docker image"
grep -q "18080:8000" "$WORKFLOW" || fail "deploy workflow must expose the CI Docker image for verification"
grep -q "scripts/verify-public-site.sh http://127.0.0.1:18080" "$WORKFLOW" || fail "deploy workflow must verify the running CI Docker image"
grep -q "scripts/check-frontend-render.sh http://127.0.0.1:18080" "$WORKFLOW" || fail "deploy workflow must browser-check the running CI Docker image"
grep -Fq "APP_VERSION='\${{ github.sha }}' bash scripts/deploy.sh" "$WORKFLOW" || fail "deploy workflow must pass APP_VERSION to remote deploys"
grep -q "scripts/check-deploy-secrets.sh" "$WORKFLOW" || fail "deploy workflow must use the shared deploy secret validator"
grep -q "DEPLOY_HOST" "$WORKFLOW" || fail "deploy workflow must document DEPLOY_HOST secret"
grep -q "DEPLOY_HOST must be a hostname or IP address" "$DEPLOY_SECRETS_SCRIPT" || fail "deploy secret validator must reject DEPLOY_HOST values with URL syntax"
grep -q "DEPLOY_HOST may only contain letters, numbers, dots, and hyphens" "$DEPLOY_SECRETS_SCRIPT" || fail "deploy secret validator must validate DEPLOY_HOST characters"
grep -q "DEPLOY_USER may only contain letters, numbers, dots, underscores, and hyphens" "$DEPLOY_SECRETS_SCRIPT" || fail "deploy secret validator must validate DEPLOY_USER characters"
grep -q "DEPLOY_SSH_KEY" "$WORKFLOW" || fail "deploy workflow must use DEPLOY_SSH_KEY secret"
grep -q "ssh-keygen -y -f" "$DEPLOY_SECRETS_SCRIPT" || fail "deploy secret validator must validate DEPLOY_SSH_KEY can be parsed"
grep -q "DEPLOY_ENV" "$WORKFLOW" || fail "deploy workflow must support DEPLOY_ENV secret"
grep -q "DEPLOY_PATH must be an absolute path" "$DEPLOY_SECRETS_SCRIPT" || fail "deploy secret validator must reject unsafe DEPLOY_PATH values"
grep -q "DEPLOY_PATH may only contain letters, numbers, slash, dot, underscore, and hyphen" "$DEPLOY_SECRETS_SCRIPT" || fail "deploy secret validator must reject DEPLOY_PATH values with unsafe shell characters"
grep -q "DEPLOY_PORT must be numeric" "$DEPLOY_SECRETS_SCRIPT" || fail "deploy secret validator must validate DEPLOY_PORT when set"
grep -q "DEPLOY_PORT must be between 1 and 65535" "$DEPLOY_SECRETS_SCRIPT" || fail "deploy secret validator must validate DEPLOY_PORT range when set"
grep -q "scripts/check-env-file.sh" "$WORKFLOW" || fail "deploy workflow must validate DEPLOY_ENV before upload"
grep -q "gh secret list" "$GITHUB_SECRETS_SCRIPT" || fail "GitHub secret checker must inspect Actions secret names with gh"
grep -q "DEPLOY_ENV is optional" "$GITHUB_SECRETS_SCRIPT" || fail "GitHub secret checker must document optional DEPLOY_ENV behavior"
grep -q "gh secret set DEPLOY_ENV <" "$GITHUB_SECRETS_COMMAND_SCRIPT" || fail "GitHub secret command printer must avoid printing DEPLOY_ENV values"
grep -q -- "--manual" "$GITHUB_SECRETS_COMMAND_SCRIPT" || fail "GitHub secret command printer must support manual web UI output"
grep -q "scripts/print-github-secrets-commands.sh" "$LAUNCH_CHECKLIST" || fail "launch checklist must document GitHub secret command generation"
grep -q -- "--manual" "$LAUNCH_CHECKLIST" || fail "launch checklist must document manual GitHub secret setup"
grep -q "trap 'rm -f \"\$RUNNER_TEMP/deploy.env\"' EXIT" "$WORKFLOW" || fail "deploy workflow must remove temporary DEPLOY_ENV files on validation failure"
grep -q "chmod 600 '\$DEPLOY_PATH/.env'" "$WORKFLOW" || fail "deploy workflow must lock down server .env permissions"
grep -q "\$DEPLOY_PATH/.env.next" "$WORKFLOW" || fail "deploy workflow must write DEPLOY_ENV to a temporary remote env file before replacing .env"
grep -Fq 'trap '"'"'rm -f \"\$tmp_env\"'"'"' EXIT' "$WORKFLOW" || fail "deploy workflow must clean temporary remote .env.next files on failure"
grep -q "mv '\$DEPLOY_PATH/.env.next' '\$DEPLOY_PATH/.env'" "$WORKFLOW" || fail "deploy workflow must atomically replace the remote .env"
grep -q "\$DEPLOY_PATH/.env.previous" "$WORKFLOW" || fail "deploy workflow must preserve the previous server .env before overwriting it"
grep -q "DEPLOY_PATH/.env" "$WORKFLOW" || fail "deploy workflow must verify the server .env exists"
grep -q "scripts/check-remote-server.sh" "$WORKFLOW" || fail "deploy workflow must use the shared remote server checker before syncing"
grep -q "scripts/check-remote-server.sh --domain-routing" "$WORKFLOW" || fail "deploy workflow must verify SITE_DOMAIN points to DEPLOY_HOST before syncing"
grep -q "command -v rsync" "$REMOTE_SERVER_SCRIPT" || fail "remote server checker must verify remote rsync is installed"
grep -q "command -v docker" "$REMOTE_SERVER_SCRIPT" || fail "remote server checker must verify remote Docker is installed"
grep -q "docker compose version" "$REMOTE_SERVER_SCRIPT" || fail "remote server checker must verify remote Docker Compose is installed"
grep -q -- "--pull-images" "$REMOTE_SERVER_SCRIPT" || fail "remote server checker must support remote Docker image pull checks"
grep -q "docker pull caddy:2" "$REMOTE_SERVER_SCRIPT" || fail "remote server checker must verify the Caddy image can pull"
grep -q -- "--check-ports" "$REMOTE_SERVER_SCRIPT" || fail "remote server checker must expose first-deploy web port checks"
grep -q "ss -ltn" "$REMOTE_SERVER_SCRIPT" || fail "remote server checker must inspect remote 80/443 listeners"
grep -q -- "--observability" "$REMOTE_SERVER_SCRIPT" || fail "remote server checker must support observability image pull checks"
grep -q "ENV_CHECK_ARGS+=(--observability)" "$REMOTE_SERVER_SCRIPT" || fail "remote server checker must validate DEPLOY_ENV with observability requirements"
grep -q "validate_remote_env_for_observability" "$REMOTE_SERVER_SCRIPT" || fail "remote server checker must validate remote .env with observability requirements"
grep -q "docker pull langfuse/langfuse:2" "$REMOTE_SERVER_SCRIPT" || fail "remote server checker must verify the Langfuse image can pull"
grep -q -- "--check-ports" "$LAUNCH_SCRIPT" || fail "launch readiness must expose first-deploy web port checks"
grep -q "REMOTE_SERVER_ARGS+=(--check-ports)" "$LAUNCH_SCRIPT" || fail "launch readiness must pass first-deploy web port checks to remote checker"
grep -q -- "--check-ports" "$LAUNCH_CHECKLIST" || fail "launch checklist must document first-deploy web port checks"
grep -Fq -- "--exclude '.env'" "$WORKFLOW" || fail "deploy workflow must not sync .env"
grep -Fq -- "--exclude '.env.*'" "$WORKFLOW" || fail "deploy workflow must not sync .env.* files"
grep -Fq -- "--exclude '.deploy.lock'" "$WORKFLOW" || fail "deploy workflow must not sync deploy locks"
grep -Fq -- "--exclude '.github'" "$WORKFLOW" || fail "deploy workflow must not sync GitHub workflow metadata"
grep -Fq -- "--exclude '.claude'" "$WORKFLOW" || fail "deploy workflow must not sync local agent metadata"
grep -Fq -- "--exclude '.agents'" "$WORKFLOW" || fail "deploy workflow must not sync local agent metadata"
grep -Fq -- "--exclude '*.log'" "$WORKFLOW" || fail "deploy workflow must not sync local logs"
grep -q "SITE_ORIGIN=https://" "$WORKFLOW" || fail "deploy workflow must build the public SITE_ORIGIN after remote deploy"
grep -q "EXPECTED_APP_VERSION=\"\${{ github.sha }}\" EXPECT_CADDY_HEADERS=1 bash scripts/verify-public-site.sh \"\$SITE_ORIGIN\"" "$WORKFLOW" || fail "deploy workflow must verify the deployed public origin from the runner"
grep -q "bash scripts/check-frontend-render.sh \"\$SITE_ORIGIN\"" "$WORKFLOW" || fail "deploy workflow must browser-check the deployed public origin from the runner"
grep -q "Collect remote diagnostics" "$WORKFLOW" || fail "deploy workflow must collect remote diagnostics when verification fails"
grep -q "docker compose ps" "$WORKFLOW" || fail "deploy workflow diagnostics must include compose service status"
grep -q "docker compose logs --tail=120 app" "$WORKFLOW" || fail "deploy workflow diagnostics must include recent app logs"
grep -q "docker compose logs --tail=120 caddy" "$WORKFLOW" || fail "deploy workflow diagnostics must include recent Caddy logs"
grep -q "SITE_DOMAIN=" "$SETUP_SCRIPT" || fail "server setup must create SITE_DOMAIN in .env"
grep -q "BLOG_DEEPSEEK_KEY=" "$SETUP_SCRIPT" || fail "server setup must create BLOG_DEEPSEEK_KEY in .env"
grep -q "validate_domain_syntax" "$SETUP_SCRIPT" || fail "server setup must validate SITE_DOMAIN syntax before writing .env"
grep -q -- "--output" "$SETUP_SCRIPT" || fail "server setup must support writing a DEPLOY_ENV output file"
grep -q -- "--output ./production.env" "$README" || fail "README must document production env output generation"
grep -q -- "--output ./production.env" "$LAUNCH_CHECKLIST" || fail "launch checklist must document production env output generation"
grep -q "resolve_domain" "$ENV_CHECK_SCRIPT" || fail "env validation must check SITE_DOMAIN DNS resolution"
grep -q -- "--skip-dns" "$PREFLIGHT_SCRIPT" || fail "preflight must support --skip-dns for local dry-runs"
grep -q -- "--observability" "$PREFLIGHT_SCRIPT" || fail "preflight must validate observability secrets when requested"
grep -q "is_placeholder_value" "$ENV_CHECK_SCRIPT" || fail "env validation must detect placeholder secrets"
grep -q "validate_domain_syntax" "$ENV_CHECK_SCRIPT" || fail "env validation must validate SITE_DOMAIN syntax"
grep -q "scripts/check-env-file.sh" "$PREFLIGHT_SCRIPT" || fail "preflight must use shared env file validation"
grep -q "docker pull caddy:2" "$PREFLIGHT_SCRIPT" || fail "preflight pull check must include the Caddy runtime image"
grep -q "docker pull postgres:16" "$PREFLIGHT_SCRIPT" || fail "observability preflight pull check must include the Postgres runtime image"
grep -q "docker pull langfuse/langfuse:2" "$PREFLIGHT_SCRIPT" || fail "observability preflight pull check must include the Langfuse runtime image"
grep -q "LANGFUSE_INIT_USER_PASSWORD" "$ENV_CHECK_SCRIPT" || fail "env validation must validate Langfuse bootstrap password"
grep -q "SITE_DOMAIN resolves" "$ENV_CHECK_SCRIPT" || fail "env validation must report resolved SITE_DOMAIN status"
grep -q "/api/version" "$VERIFY_SCRIPT" || fail "public verification must check /api/version"
grep -q "EXPECTED_APP_VERSION" "$VERIFY_SCRIPT" || fail "public verification must support EXPECTED_APP_VERSION"
grep -q "EXPECT_CADDY_HEADERS" "$VERIFY_SCRIPT" || fail "public verification must support Caddy header checks"
grep -q "publishing cache header" "$VERIFY_SCRIPT" || fail "public verification must check publishing metadata cache headers"
! grep -q '^HOME=' "$VERIFY_SCRIPT" || fail "public verification must not overwrite HOME"
! grep -q '^HOME=' "$ROOT_DIR/scripts/smoke-production.sh" || fail "production smoke test must not overwrite HOME"
grep -q "/api/posts" "$VERIFY_SCRIPT" || fail "public verification must check /api/posts"
grep -q 'id="root"' "$VERIFY_SCRIPT" || fail "public verification must check the frontend app shell"
grep -q "Shouka Blog | AI, Writing, Finance" "$VERIFY_SCRIPT" || fail "public verification must check the deployed HTML title"
grep -q "canonical" "$VERIFY_SCRIPT" || fail "public verification must check the deployed canonical URL"
grep -q "og:url" "$VERIFY_SCRIPT" || fail "public verification must check deployed Open Graph URL"
grep -q "og:image" "$VERIFY_SCRIPT" || fail "public verification must check deployed Open Graph metadata"
grep -q "twitter:card" "$VERIFY_SCRIPT" || fail "public verification must check deployed Twitter metadata"
grep -q "twitter:image" "$VERIFY_SCRIPT" || fail "public verification must check deployed Twitter image metadata"
grep -q "share image asset" "$VERIFY_SCRIPT" || fail "public verification must check the deployed share image asset is reachable"
grep -q "/feed.xml" "$VERIFY_SCRIPT" || fail "public verification must check /feed.xml"
grep -q "/robots.txt" "$VERIFY_SCRIPT" || fail "public verification must check /robots.txt"
grep -q "/sitemap.xml" "$VERIFY_SCRIPT" || fail "public verification must check /sitemap.xml"
grep -q "scripts/verify-public-site.sh" "$DEPLOY_SCRIPT" || fail "deploy script must run public site verification"
grep -q -- "--browser-check" "$DEPLOY_SCRIPT" || fail "deploy script must expose optional browser render verification"
grep -q "scripts/check-frontend-render.sh" "$DEPLOY_SCRIPT" || fail "deploy script must support browser render verification"
grep -q "APP_VERSION=" "$DEPLOY_SCRIPT" || fail "deploy script must export APP_VERSION"
grep -q "EXPECTED_APP_VERSION" "$DEPLOY_SCRIPT" || fail "deploy script must pass EXPECTED_APP_VERSION to public verification"
grep -q "EXPECT_CADDY_HEADERS" "$DEPLOY_SCRIPT" || fail "deploy script must enable Caddy header checks"
grep -q "print_diagnostics" "$DEPLOY_SCRIPT" || fail "deploy script must print diagnostics on failure"
grep -q "compose up failed" "$DEPLOY_SCRIPT" || fail "deploy script must print diagnostics when compose up fails"
grep -q "docker compose logs --tail" "$DEPLOY_SCRIPT" || fail "deploy script must include recent service logs in diagnostics"
grep -q ".deploy.lock" "$DEPLOY_SCRIPT" || fail "deploy script must use a deployment lock"
grep -q "acquire_lock" "$DEPLOY_SCRIPT" || fail "deploy script must acquire a deployment lock"
grep -q "release_lock" "$DEPLOY_SCRIPT" || fail "deploy script must release the deployment lock"
grep -q -- "--skip-dns" "$DEPLOY_SCRIPT" || fail "deploy dry-runs must skip DNS resolution"
grep -q "PREFLIGHT_ARGS+=(--observability)" "$DEPLOY_SCRIPT" || fail "deploy script must pass observability mode to preflight"
grep -q "EXPECTED_APP_VERSION" "$WORKFLOW" || fail "deploy workflow must verify the expected APP_VERSION"
grep -q "^\\.env$" "$DOCKERIGNORE" || fail ".dockerignore must exclude .env"
grep -q "^\\.env\\.\\*$" "$DOCKERIGNORE" || fail ".dockerignore must exclude .env.*"
grep -q "^production\\.env$" "$DOCKERIGNORE" || fail ".dockerignore must exclude production.env"
grep -q "^\\.deploy\\.lock$" "$DOCKERIGNORE" || fail ".dockerignore must exclude deploy locks"
grep -q "^\\.github$" "$DOCKERIGNORE" || fail ".dockerignore must exclude .github"
grep -q "^\\.claude$" "$DOCKERIGNORE" || fail ".dockerignore must exclude .claude"
grep -q "^\\.agents$" "$DOCKERIGNORE" || fail ".dockerignore must exclude .agents"
grep -q "^\\*\\*/\\.pytest_cache$" "$DOCKERIGNORE" || fail ".dockerignore must exclude pytest caches"
grep -q "^\\*\\.log$" "$DOCKERIGNORE" || fail ".dockerignore must exclude logs"
grep -q "^\\*\\.tsbuildinfo$" "$DOCKERIGNORE" || fail ".dockerignore must exclude TypeScript build info"
grep -q "^\\.env$" "$GITIGNORE" || fail ".gitignore must exclude root .env"
grep -q "^\\.env\\.\\*$" "$GITIGNORE" || fail ".gitignore must exclude .env.*"
grep -q "^production\\.env$" "$GITIGNORE" || fail ".gitignore must exclude production.env"
grep -q "^\\.deploy\\.lock$" "$GITIGNORE" || fail ".gitignore must exclude deploy locks"
grep -q "^\\*\\.tsbuildinfo$" "$GITIGNORE" || fail ".gitignore must exclude TypeScript build info"
if git -C "$ROOT_DIR" ls-files '*tsbuildinfo' | grep -q .; then
  fail "TypeScript build info files must not be tracked"
fi
grep -q "^HEALTHCHECK " "$DOCKERFILE" || fail "Dockerfile must include a container healthcheck"
grep -q "/api/health" "$DOCKERFILE" || fail "Dockerfile healthcheck must call /api/health"
grep -q "^ARG APP_VERSION=local$" "$DOCKERFILE" || fail "Dockerfile must declare APP_VERSION build arg"
grep -q '^ENV APP_VERSION=\$APP_VERSION$' "$DOCKERFILE" || fail "Dockerfile must persist APP_VERSION"
grep -q "Strict-Transport-Security" "$CADDYFILE" || fail "Caddyfile must set HSTS"
grep -q "X-Content-Type-Options" "$CADDYFILE" || fail "Caddyfile must set nosniff"
grep -q "Referrer-Policy" "$CADDYFILE" || fail "Caddyfile must set a referrer policy"
grep -q "Cache-Control" "$CADDYFILE" || fail "Caddyfile must set cache headers"
grep -q "/assets/\\*" "$CADDYFILE" || fail "Caddyfile must cache Vite assets"
grep -q "caddy_data:/data" "$COMPOSE_FILE" || fail "docker compose must persist Caddy certificate data"
grep -q "caddy_config:/config" "$COMPOSE_FILE" || fail "docker compose must persist Caddy runtime config"
grep -q "^  caddy_config:$" "$COMPOSE_FILE" || fail "docker compose must declare the caddy_config volume"
awk '/^  app:/{in_app=1} /^  caddy:/{in_app=0} in_app {print}' "$COMPOSE_FILE" | grep -q "SITE_DOMAIN: \${SITE_DOMAIN:-shoka.example.com}" || fail "docker compose app service must receive SITE_DOMAIN for public URLs"
grep -q "driver: json-file" "$COMPOSE_FILE" || fail "docker compose must configure log rotation for production services"
grep -q "max-size: \"10m\"" "$COMPOSE_FILE" || fail "docker compose log rotation must set max-size"
grep -q "max-file: \"3\"" "$COMPOSE_FILE" || fail "docker compose log rotation must set max-file"
grep -q "scripts/verify-release.sh" "$README" || fail "README must document release verification"
grep -q "scripts/smoke-caddy-proxy.sh" "$README" || fail "README must document the Caddy reverse proxy smoke test"
grep -q "scripts/check-launch-readiness.sh" "$README" || fail "README must document launch readiness checks"
grep -q "scripts/check-frontend-render.sh https://your-domain.com" "$README" || fail "README must document public browser render verification"
grep -q "docs/launch-checklist.md" "$README" || fail "README must link to the launch checklist"
grep -q "DEPLOY_HOST" "$LAUNCH_CHECKLIST" || fail "launch checklist must mention DEPLOY_HOST"
grep -q "DEPLOY_ENV" "$LAUNCH_CHECKLIST" || fail "launch checklist must mention DEPLOY_ENV"
grep -q "authorized_keys" "$LAUNCH_CHECKLIST" || fail "launch checklist must mention installing the deploy SSH public key"
grep -q "authorized_keys" "$README" || fail "README must mention installing the deploy SSH public key"
grep -q "scripts/check-launch-readiness.sh" "$LAUNCH_CHECKLIST" || fail "launch checklist must include launch readiness verification"
grep -q "scripts/check-github-secrets.sh" "$LAUNCH_CHECKLIST" || fail "launch checklist must include GitHub secret name verification"
grep -q "scripts/verify-public-site.sh" "$LAUNCH_CHECKLIST" || fail "launch checklist must include public site verification"
grep -q -- "--browser-check" "$LAUNCH_CHECKLIST" || fail "launch checklist must explain optional browser-check deployment mode"
grep -q "Rollback" "$LAUNCH_CHECKLIST" || fail "launch checklist must include rollback notes"
grep -q "scripts/rollback-env.sh" "$LAUNCH_CHECKLIST" || fail "launch checklist must include the rollback env command"

bash "$SEO_SCRIPT"

pass "deploy workflow exists and contains required checks"
